
package ec.edu.ups.vista.reservacion;

import ec.edu.ups.controladores.ControladorReservacion;
import ec.edu.ups.modelo.Reserva;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class CrearReservacion extends javax.swing.JInternalFrame {
     private ResourceBundle mensajes;
    /**
     * Creates new form CrearReservacion
     */
    private ControladorReservacion controladorReservacion;
    
        public CrearReservacion(ControladorReservacion controladorReservacion,ResourceBundle mensajes) {
        initComponents();
        this. mensajes = mensajes;
        cambiarIdioma (mensajes);
        this.controladorReservacion= controladorReservacion;
         txtCodigo.setText(Integer.toString(controladorReservacion.getCodigo()));
    }
         public void cambiarIdioma(ResourceBundle mensajes){
   jlbCrearReservacion.setText(mensajes.getString("Ventana.TituloCrear.Reservacion"));
   jblCodigoCrearReservacion.setText(mensajes.getString("Ventana.CrearR.Reservacion"));
   btnCrear.setText(mensajes.getString("Ventana.CrearR.Reservacion"));
   jlbCodigoHabitacion.setText(mensajes.getString("Ventanas.CodigoH"));
   jblCodigoTrabajador.setText(mensajes.getString("Ventanas.CodigoEH"));
   jblFechaReserva.setText(mensajes.getString("Ventanas.FechaR"));
   jlbFechaIngreso.setText(mensajes.getString("Ventanas.FechaI"));
   jlbFechaSalida.setText(mensajes.getString("Ventanas.FechaS"));
   jlbCostoAlojamiento.setText(mensajes.getString("Ventanas.CostoR"));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblCodigoCrearReservacion = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jlbCodigoHabitacion = new javax.swing.JLabel();
        txtCodiHabitacion = new javax.swing.JTextField();
        jblCodigoTrabajador = new javax.swing.JLabel();
        txtFechIngre = new javax.swing.JTextField();
        jblFechaReserva = new javax.swing.JLabel();
        txtCodTrabaador = new javax.swing.JTextField();
        jlbFechaSalida = new javax.swing.JLabel();
        txtFechReser = new javax.swing.JTextField();
        jlbFechaIngreso = new javax.swing.JLabel();
        txtCosAloj = new javax.swing.JTextField();
        jlbCostoAlojamiento = new javax.swing.JLabel();
        txtFechSal = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jlbCrearReservacion = new javax.swing.JLabel();

        setClosable(true);

        jblCodigoCrearReservacion.setText("CODIGO :");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jlbCodigoHabitacion.setText("CODIGO HABITACION :");

        txtCodiHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodiHabitacionActionPerformed(evt);
            }
        });

        jblCodigoTrabajador.setText("CODIGO TRABAJADOR :");

        jblFechaReserva.setText("FECHA DE RESERVA :");

        jlbFechaSalida.setText("FECHA DE SALIDA  :");

        jlbFechaIngreso.setText("FECHA DE INGRESO :");

        jlbCostoAlojamiento.setText("COSTO DE ALOJAMIENTO :");

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jlbCrearReservacion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbCrearReservacion.setText("CREAR RESERVACION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jlbCostoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jblCodigoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jblFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbCodigoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jblCodigoCrearReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCosAloj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodiHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodTrabaador, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFechReser)
                                .addComponent(txtFechIngre)
                                .addComponent(txtFechSal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnCrear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jlbCrearReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlbCrearReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCodigoCrearReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodiHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCodigoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodTrabaador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechReser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechSal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCostoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosAloj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnCrear)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Reserva reserva = new Reserva();
        reserva.setCodigoReserva(Integer.parseInt(txtCodigo.getText()));
        reserva.setCodigoHabitacion(Integer.parseInt(txtCodiHabitacion.getText()));
        reserva.setCodigoTrabajador(Integer.parseInt(txtCodTrabaador.getText()));
        reserva.setFechaReserva((txtFechReser.getText()));
        reserva.setFechaIngreso(txtFechIngre.getText());
        reserva.setFechaSalida(txtFechSal.getText());
        reserva.setCostoAlojamiento(Double.parseDouble(txtCosAloj.getText()));
        txtCodigo.setText(String.valueOf(reserva.getCodigoReserva()));
        controladorReservacion.create(reserva);
        txtCodigo.setText(Integer.toString(this.controladorReservacion.getCodigo()));
        JOptionPane.showMessageDialog(this, "RESERRVACION CREADA", "Crear RESERVACION", JOptionPane.INFORMATION_MESSAGE);
        txtCodigo.setText(String.valueOf(this.controladorReservacion.getCodigo()));
        txtCodiHabitacion.setText("");
        txtCodTrabaador.setText("");
        txtFechReser.setText("");
        txtFechIngre.setText("");
        txtFechSal.setText("");
        txtCosAloj.setText("");
           // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodiHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodiHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodiHabitacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblCodigoCrearReservacion;
    private javax.swing.JLabel jblCodigoTrabajador;
    private javax.swing.JLabel jblFechaReserva;
    private javax.swing.JLabel jlbCodigoHabitacion;
    private javax.swing.JLabel jlbCostoAlojamiento;
    private javax.swing.JLabel jlbCrearReservacion;
    private javax.swing.JLabel jlbFechaIngreso;
    private javax.swing.JLabel jlbFechaSalida;
    private javax.swing.JTextField txtCodTrabaador;
    private javax.swing.JTextField txtCodiHabitacion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosAloj;
    private javax.swing.JTextField txtFechIngre;
    private javax.swing.JTextField txtFechReser;
    private javax.swing.JTextField txtFechSal;
    // End of variables declaration//GEN-END:variables
}
