/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.reservacion;

import ec.edu.ups.controladores.ControladorReservacion;
import ec.edu.ups.modelo.Producto;
import ec.edu.ups.modelo.Reserva;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class LIstarReservacion extends javax.swing.JInternalFrame {
    private ControladorReservacion controladorReservacion;
    /**
     * Creates new form LIstarReservacion
     */
    public LIstarReservacion(ControladorReservacion controladorReservacion) {
        initComponents();
        this.controladorReservacion=controladorReservacion;
        llenarDatos();
    }
     public void llenarDatos(){
        DefaultTableModel modelo=(DefaultTableModel)tbtListarReserva.getModel();
        Set<Reserva>lista=controladorReservacion.getLista();
         for(Reserva reserva:lista){
        Object[]datos={reserva.getCodigoReserva(),reserva.getCodigoHabitacion(),reserva.getCodigoTrabajador(),
            reserva.getFechaIngreso(),reserva.getFechaIngreso(),reserva.getFechaSalida(),reserva.getCostoAlojamiento()};
            modelo.addRow(datos);
     }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtListarReserva = new javax.swing.JTable();

        setClosable(true);

        tbtListarReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO RESERVA", "CODIGO HABITACIÓN", "CODIGO TRABAJADOR", "FECHA RESERVA", "FECHA INGRESO ", "FECHA SALIDA", "COSTO"
            }
        ));
        jScrollPane1.setViewportView(tbtListarReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtListarReserva;
    // End of variables declaration//GEN-END:variables
}
