/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.reservacion;

import ec.edu.ups.controladores.ControladorReservacion;
import ec.edu.ups.modelo.Habitacion;
import ec.edu.ups.modelo.Reserva;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class LIstarReservacion extends javax.swing.JInternalFrame {
    private ControladorReservacion controladorReservacion;
     private ResourceBundle mensajes;
    /**
     * Creates new form LIstarReservacion
     */
    public LIstarReservacion(ControladorReservacion controladorReservacion,ResourceBundle mensajes) {
        initComponents();
        this.controladorReservacion=controladorReservacion;
        llenarDatos();
        this. mensajes = mensajes;
        cambiarIdioma (mensajes);
    }
     public void llenarDatos(){
        DefaultTableModel modelo=(DefaultTableModel)tbtListarReserva.getModel();
        Set<Reserva>lista=controladorReservacion.getLista();
         for(Reserva reserva:lista){
        Object[]datos={reserva.getCodigoReserva(),reserva.getCodigoHabitacion(),reserva.getCodigoTrabajador(),
            reserva.getFechaIngreso(),reserva.getFechaIngreso(),reserva.getFechaSalida(),reserva.getCostoAlojamiento()};
            modelo.addRow(datos);
     
            
         }
     }
     public void cambiarIdioma(ResourceBundle mensajes){
         btnListarReservacion.setText(mensajes.getString("Ventana.ListarR.Reservacion"));
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtListarReserva = new javax.swing.JTable();
        btnListarReservacion = new javax.swing.JLabel();

        setClosable(true);

        tbtListarReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO RESERVA", "CODIGO HABITACIÓN", "CODIGO TRABAJADOR", "FECHA RESERVA", "FECHA INGRESO ", "FECHA SALIDA", "COSTO"
            }
        ));
        jScrollPane1.setViewportView(tbtListarReserva);

        btnListarReservacion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnListarReservacion.setText("LISTAR RESERVACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnListarReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnListarReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnListarReservacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtListarReserva;
    // End of variables declaration//GEN-END:variables
}
