/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.empleado;

import ec.edu.ups.vista.cliente.*;
import ec.edu.ups.controladores.ControladorEmpleado;
import ec.edu.ups.modelo.Empleado;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class ListarEmpleado extends javax.swing.JInternalFrame {
 private ControladorEmpleado controladorEmpleado;
 private ResourceBundle mensajes;
    /**
     * Creates new form ListarClientes
     */
    public ListarEmpleado(ControladorEmpleado controladorEmpleado,ResourceBundle mensajes) {
        initComponents();
        this.controladorEmpleado=controladorEmpleado;
        llenarDatos();
         this.mensajes = mensajes;
        cambiarIdioma(mensajes);
       
    }
     public void cambiarIdioma(ResourceBundle mensajes){
     jlbTituloListaCliente.setText(mensajes.getString("Ventanas.Titulo.ListaE"));    
     }
   
    public void llenarDatos(){
        DefaultTableModel modelo=(DefaultTableModel)tblEmpleado.getModel();
        Set<Empleado>lista=controladorEmpleado.getLista();
        for(Empleado empleado:lista){
            Object[]datos={empleado.getCodigo(),
                empleado.getCedula(),empleado.getNombre(),
                empleado.getDireccion(),empleado.getTelefono()};
            
             modelo.addRow(datos);
            
        }
        
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        jlbTituloListaCliente = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cedula", "Nombre", "Direccion", "Telefono", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleado);

        jlbTituloListaCliente.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbTituloListaCliente.setText("LISTA EMPLEADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jlbTituloListaCliente))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTituloListaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbTituloListaCliente;
    private javax.swing.JTable tblEmpleado;
    // End of variables declaration//GEN-END:variables
}
